### ISSUE TITLE
Provide a shim file

### ISSUE THREAD

**Issue by kamilmysliwiec** [nestjs/swagger#1037]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Expected behavior

Something similar to what `@nestjs/graphql` provides.

More on that topic https://github.com/nestjs/graphql/issues/1082
Example implementation: https://github.com/nestjs/graphql/pull/1184/files

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mkhraisha** [comment]
are there any updates on this?

**Comment by nick-lehmann** [comment]
@kamilmysliwiec would you accept a merge request for this? We have created a small shim file for this package at work that includes all the exports we need. I guess I could start from there, add the remaining exports and submit a pull request later this week.

**Comment by jmcdo29** [comment]
@nick-lehmann that sounds great! Thanks for the help

**Comment by nick-lehmann** [comment]
Is there a reason why the [shim file](https://github.com/maayanbar13/graphql/blob/e98f3ec6c78c5ff9a8ebefc503c67d99ab4f5bc2/lib/extra/graphql-model-shim.ts) for `@nestjs/graphql` is written in typescript, unlike the [typeorm shim](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js) plain javascript? As far as I can tell, the arguments for the decorators do not need any type information at build time and it would make the shim file quite a lot easier. So instead of 

```typescript
# shim.ts
export function Directive(sdl: string,
    ): MethodDecorator & PropertyDecorator & ClassDecorator {
    return (target: Function | Object, key?: string | symbol) => {}
}
```

one could simply do

```javascript
# shim.js
function Directive() {
    return () => {}
}
exports.Directive = Directive
```

The second way is how I have done it so far and it is working fine for us.

**Comment by kamilmysliwiec** [comment]
Either approach should be fine. What issues did you run into when using `ts` files?

**Comment by nick-lehmann** [comment]
Sorry for the late reply. I added the shim file and created a pull request for it.

No, I did not experience any issues with the typescript file. I just wondered if there might be any downside that I did not think of.

**Comment by kamilmysliwiec** [comment]
Thanks @nick-lehmann! Let's track this here https://github.com/nestjs/swagger/pull/1505
