### ISSUE TITLE
Add Headers to the reponse

### ISSUE THREAD

**Issue by alfirin** [nestjs/swagger#113]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
Overflow.
</code></pre>

## Expected behavior
I want to set the returned headers in the response.

For example inside `ApiResponse` we could have an array of headers to add to the documentation.

In swagger we can do that, ex: https://swagger.io/docs/specification/describing-responses/

**Comment by kamilmysliwiec** [comment]
It'll be fixed in the incoming release.

**Comment by kamilmysliwiec** [comment]
`2.3.0` is available already

**Comment by villelahdenvuo** [comment]
@kamilmysliwiec Hey, I noticed that headers is defined in `ApiResponse` decorator, but it's not in the `ResponseMetadata` interface, thus although it should work, you cannot do: `ApiOkResponse({ dsecription: 'Succcess!', headers: { ... } })` because the headers is missing from the `ResponseMetadata` interface.

**Comment by alfirin** [comment]
I agree with you @villelahdenvuo !

**Comment by villelahdenvuo** [comment]
I opened a simple PR to fix this: https://github.com/nestjs/swagger/pull/286
