### ISSUE TITLE
enumName in ApiParam leaking to the OpenAPI JSON

### ISSUE THREAD

**Issue by murbanowicz** [nestjs/swagger#1148]
Using 
```
  @ApiParam({
    name: 'foo',
    enum: FooEnum,
    enumName: 'FooEnum',
  })
```
results in having `enumName` in OpenAPI spec which will fail most of the validation scripts as this should not be there.

Reproduction repo: https://github.com/murbanowicz/nest-swagger-param-enumname/blob/main/test/app.e2e-spec.ts#L25

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Sharakai** [comment]
Looks like @tombarton has [raised a PR](https://github.com/nestjs/swagger/pull/1279) to fix this. This issue is causing problems when generating client code using the `openapi-generator-cli` with a controller containing enum API parameters with `"enumName"`, e.g:
```ts
@ApiParam({
  name: "type",
  enum: ResouceType,
  enumName: "ResourceType",
})
```
@nartc would you have time to get some 👀 on this?

**Comment by kamilmysliwiec** [comment]
Tracking this here https://github.com/nestjs/swagger/pull/1279
