### ISSUE TITLE
Add support for defining DTO's directly in controller files 

### ISSUE THREAD

**Issue by Agreon** [nestjs/swagger#1193]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

If i want to define the DTOs for a controller response in the same file of the controller the cli plugin won't infer the DTO.

This is due the early return in [compiler-plugin.ts](https://github.com/nestjs/swagger/blob/master/lib/plugin/compiler-plugin.ts#L17)

```
      if (isFilenameMatched(options.dtoFileNameSuffix, sf.fileName)) {
        return modelClassVisitor.visit(sf, ctx, program, options);
      }
      if (isFilenameMatched(options.controllerFileNameSuffix, sf.fileName)) {
        return controllerClassVisitor.visit(sf, ctx, program, options);
      }
```

## Expected behavior

One can define the DTOs in the same file as the controller.

## Minimal reproduction of the problem with instructions

Add the following options to the `nest-cli.json` swagger plugin entry:

```
"options": {
    "dtoFileNameSuffix": ["controller.ts"],
    "controllerFileNameSuffix": ["controller.ts"]
}
```

Create a controller with a DTO that is returned by a route of the controller.

## What is the motivation / use case for changing the behavior?

Not having to create separate files for DTOs.

## Environment

<pre><code>
Nest version: 7.6.11
Nest-Swagger version: 4.7.12

**Comment by kamilmysliwiec** [comment]
This would have a significant impact on the performance and since having DTO classes in the same file as a controller class is considered as bad practice (actually having multiple classes in a single file regardless of their behavior/applications will be reported as an error with the default linter config), we don't plan to address this in the foreseeable future.

If you have some time & want to contribute, feel free to create a PR with this feature added under a flag (an additional configuration property would be needed so we won't run all visitors by default).
