### ISSUE TITLE
Wrong typing for docExpansion option

### ISSUE THREAD

**Issue by GustavoContreiras** [nestjs/swagger#1875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The autocomplete on vscode shows that the `docExpansion` option should be under `uiConfig`.
But in this post we found that it should be under `swaggerOptions`.

https://github.com/nestjs/nest/issues/9421

### Minimum reproduction code

https://github.com/nestjs/nest/issues/9421

### Expected behavior

We should see the autocomplete option under `swaggerOptions`

![image](https://user-images.githubusercontent.com/38460351/161262745-ce7f1fad-03a6-4c5d-9b01-26c851d50271.png)

Not under `uiConfig`

![image](https://user-images.githubusercontent.com/38460351/161262855-e5dd31d9-c0d8-4df3-9916-527c5976b18c.png)

### Package version

"@nestjs/swagger": "^5.1.5", "swagger-ui-express": "^4.2.0",

### NestJS version

"@nestjs/core": "^8.2.3"

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Can you create a PR for this issue?

**Comment by micalevisk** [comment]
the issue here is that that `uiConfig` came from `FastifySwaggerCustomOptions` and the swagger options has this type:

https://github.com/nestjs/swagger/blob/ebd3885b3da92418bd29c4fb0f5543a5843952bc/lib/interfaces/swagger-custom-options.interface.ts#L58-L60

But there's no way to tell to `SwaggerModule.setup` that we want to use `ExpressSwaggerCustomOptions` instead

What about this interface:

![image](https://user-images.githubusercontent.com/13461315/161264660-ca8fdcf8-6c91-4591-9dbf-87d21653949c.png)

I can't think of any other way to fix this

**Comment by micalevisk** [comment]
Or we could have this interface:

```
SwaggerModule.setup<'express'>(...)
```

but this one will be less flexbile.

**Comment by kamilmysliwiec** [comment]
This should be fixed in this PR https://github.com/nestjs/swagger/pull/1886
