### ISSUE TITLE
How to make inheritance work 

### ISSUE THREAD

**Issue by TomWebbio** [nestjs/swagger#223]
Hi, 

I'd like to use inheritance for my NestJs API but Swagger isn't picking up the different classes and showing them as Models. 

I have a BaseModule that I extend in other classes, Swagger only shows the BaseModule in the Model definitions. Here's an example:

```
@ApiModelProperty({ type: [BaseModule] })
public baseModules: BaseModule[];
```

Now I extend a different class with the base module like so:
`export class InfoHeaderModule extends BaseModule {`

Then I add the InfoHeader class to the array of BaseModules. This all works fine but when I look in the Swagger Models I don't see InfoHeader. This makes sense because it's probably difficult to pick up derived classed like this using reflection.

My question is, how can I make this work so that Swagger picks up the InfoHeadeModule class and not just the BaseModule?  

Is this possible, or is it a feature request?

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by mattwerthva** [comment]
I have a similar problem.  I have a web method which takes an `doWork( expression: AbstractExpression)`.  Swagger includes AbstractExpression in Models.  I have several subclasses which extend AbstractExpression, like PropertyExpression, StringExpression, etc, just subclasses.  When I call my web method I'm wanting to receive a subclass expression like StringExpression.

The problem is that swagger is not including the extended subclasses in the list of Models because they are not directly referenced.  How can I tell nestjs/swagger to explicitly include these extra models?
