### ISSUE TITLE
@Body('param') doesn't generate params in swagger

### ISSUE THREAD

**Issue by leozhao0709** [nestjs/swagger#235]
Hello, I have the following code

```
@Post('/cart')
async postCart(@Body('productId') productId: string, @Res() res: Response) {
    const product = this.shopService.getProductById(productId);
    if (product) {
      await this.cartService.addToCart(product);
      res.redirect('/shop/cart');
    }
 }
```

Then in the swagger ui, it shows no params for this endpoint. But actually, there is a `'productId'` params.

 I thought  it should work like `@Query('param')` or `@Param('param')`, for these 2 decorator, I can directly see the params shows in swagger ui.

Is there a way quickly to setup the `@Body('param')` instead of creating a DTO class?

version:
```
"@nestjs/common": "^6.0.0",
"@nestjs/core": "^6.0.0",
"@nestjs/platform-express": "^6.0.0",
"@nestjs/swagger": "^3.0.2",
"swagger-ui-express": "^4.0.2"
```

**Comment by nartc** [comment]
Try `ApiImplicitBody`?

**Comment by leozhao0709** [comment]
I've tried `@ApiImplicitBody({ name: 'productId', type: String })`, but in the swagger dashboard, it gives  productId, but it's a string, not {'productId': string}. 

If I changed type to something `@ApiImplicitBody({ name: 'productId', type: {productId: String} })`, then it can't pass the compile.

**Comment by nartc** [comment]
`@ApiImplicitBody({name: 'productId', type: String})` is what you need. 

When you say `@Body('productId') productId: string`, what you get is `req.body['productId']` so it's really just a `string`, not an object `{productId: string}`

**Comment by leozhao0709** [comment]
ok, got it. If that's the case, then it's fine. 

But still wish to have the `@Body` feature like `@Param` and `@Query` work and do not need to specify using `@ApiImplicitBody` :)

**Comment by nartc** [comment]
It's just how the library is implemented right now. `@Param` and `@Query` are a bit more straightforward than a `@Body` because the other two are interpreted as `string` so it's easy for Nest Swagger to pick them up and display them in the UI. `@Body` can be a breadth of things and Nest Swagger doesn't reflect the type on the parameters (`string`, `number`) so you have to, unfortunately, tell Swagger that the `Body` is only a string with `ApiImplicitBody`.

Note: `String` is used in the `ApiImplicitBody` decorator :)

**Comment by leozhao0709** [comment]
ah, got it. Thanks for you explanation. I think we can close this one now 👍
