### ISSUE TITLE
Swagger documentation excludes any properties that uses the Matches class validator

### ISSUE THREAD

**Issue by abdelrahmansafwat** [nestjs/swagger#2723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If there is a type that has a property validated with Match class-validator, that property is ignored by Swagger altogether.

### Minimum reproduction code

https://github.com/abdelrahmansafwat/matches-bug-repro

### Steps to reproduce

1. yarn install
2. yarn start
3. Navigate to http://localhost:3000/docs
4. Check CreateDemoDto in Schemas

### Expected behavior

The schema should be:
```
{
  name: string;
  age?: number;
}
```

### Package version

7.1.16

### NestJS version

10.0.0

### Node.js version

18.18.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

![284561800-20f03035-5a6b-4271-9da6-4732f2338101](https://github.com/nestjs/swagger/assets/33398534/d80f4d29-5e2c-426f-8d6d-5aabe2c32fc4)
![284561700-22dc9e81-a7cd-4994-9f19-f3818d9100d9](https://github.com/nestjs/swagger/assets/33398534/0f5688b9-b5fe-43c5-b735-847abe961e59)

**Comment by quangtran88** [comment]
The root cause lies in the following line:
https://github.com/nestjs/swagger/blob/33bec34405a61910a463cf2927a7f2494b066f10/lib/plugin/visitors/model-class.visitor.ts#L673
When the first argument is a chained expression, `head(decoratorArguments).text` resolves to `undefined`. To address this issue, we can use the getText() method for a safer extraction of the pattern information passed in the first argument. For example:
- `@Matches(a.b.c)` will resolve as `"a.b.c"` (instead of `undefined` using `.text`)
- `@Matches(a)` will resolve as `"a"` (same as using `.text`)
- `@Matches(/^[+]?abc$/)` will resolve as `"/^[+]?abc$/"` (same as using `.text`)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2747
