### ISSUE TITLE
Custom `type` is not retained as type, but rewritten as `allOf: - $ref: ...` breaking `nullable: true` spec in `@ApiProperty`

### ISSUE THREAD

**Issue by gregoryorton-ws** [nestjs/swagger#2948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Custom `type` is not retained as type, but rewritten as `allOf: - $ref: ...` breaking `nullable: true` spec in `@ApiProperty`

In `@ApiProperty` when using something like:

```ts
@ApiProperty({ nullable: true, type: MyCustomDto })
readonly myVar: MyCustomDto | null;
...
```

the rendered openapi.yaml is like:

```yml
myVar:
  nullable: true
  allOf:
     - $ref: "#/components/schemas/MyCustomDto"
```

tools like [Redoc.ly](https://redoc.ly/) then start to throw errors: 

<img width="832" alt="image" src="https://github.com/nestjs/swagger/assets/159014773/a58cdd28-3a82-48cc-abd1-e817da2c22e5">

### Minimum reproduction code

https://nothing.com

### Steps to reproduce

see above

### Expected behavior

```yml
myVar:
  type: object
  properties:
    id:
      type: integer
```

### Package version

7.3.0

### NestJS version

10.3.3

### Node.js version

20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

maybe related: https://github.com/nestjs/swagger/issues/2645
maybe related: https://github.com/nestjs/swagger/pull/2646

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by gregoryorton-ws** [comment]
Sure, but I don't know what the solution would be here - 

what should be the value of `type`?

**Comment by gregoryorton-ws** [comment]
One solution looks like:

```
myVar:
  nullable: true
  allOf:
    - $ref: "#/components/schemas/MyCustomDto"
    - type: object
```

I will test with redoc.ly to see if it's acceptable. If it is, then I think we can just add this `type` to the output for the custom type.

**Comment by gregoryorton-ws** [comment]
The only think redoc.ly will accept is:

```
myVar:
  nullable: true
  type: object
  allOf:
    - $ref: "#/components/schemas/MyCustomDto"
```

**Comment by clintonb** [comment]
Here is the source of our woes:
https://github.com/nestjs/swagger/blob/540490563b73aae942e00495647ecd675c42eb21/lib/services/schema-object-factory.ts#L368-L379

Extra keys that are not in the set of `['type', 'isArray', 'required']` will result in an `allOf` instead of a direct `$ref`. In this case (and #2645), the key is `nullable`. In my case, it's `name`.

The list of supported keys needs to be expanded, or removed altogether. I'm not sure which one as I haven't read the OpenAPI spec to any level of detail.

**Comment by armaniito** [comment]
Hello, i have the same issue as well. Setting a property other than "type, isArray, required" results in an allOf, causing my DTO schemas to lack the reference to another DTO. This causes problems with OpenAPI Generator because it generates the same models twice, except the file names are different.

It would be greatly appreciated if there could be a fix for this so that we get a $ref instead of an allOf.

Thank you very much

**Comment by MorelSerge** [comment]
> The only think redoc.ly will accept is:
> 
> ```
> myVar:
>   nullable: true
>   type: object
>   allOf:
>     - $ref: "#/components/schemas/MyCustomDto"
> ```
> 
> so it seems like an easy fix

This is indeed accepted, but breaks UIs as the `type=object` no longer "opens up" the nested object.

**Comment by PierreKiwi** [comment]
Same issue with `description`.

With `description` set like this
```typescript
@ApiProperty({ description: "Pagination details.", type: PaginationOutputDto })
```

The result is
<img width="323" alt="image" src="https://github.com/user-attachments/assets/a318e968-051f-46a8-9dfc-4ab24a1dd93e">

Without `description` and just the `type` like this
```
@ApiProperty({ type: PaginationOutputDto })
```

The result is 
<img width="356" alt="image" src="https://github.com/user-attachments/assets/e46e3792-84b6-46af-a9f9-31f976ab020f">
