### ISSUE TITLE
Lodash as a dependency instead of a peer dependency

### ISSUE THREAD

**Issue by mtpultz** [nestjs/swagger#3]
Is it possible to make lodash a dependency instead of a peer dependency?  On some teams lodash is used, but on others you might use Ramda, and not want to have both available to developers for consumption.

**Comment by wbhob** [comment]
+1 on this. Peer dependencies should only be used when you are _certain_ that most projects will have what you need, and may have varying versions (for example, angularfire2 has angular/core as a peer dependency because your project must have it to function otherwise.) Lodash does not have this issue, because our projects may not depend on lodash out of the box, and the changes between versions are relatively minimal.

**Comment by kamilmysliwiec** [comment]
hi! @wbhob @mtpultz that's true 🙂 I changed this in `1.1.0`. Thanks 🌮
