### ISSUE TITLE
Cannot use nested objects in response

### ISSUE THREAD

**Issue by matthew-kaye** [nestjs/swagger#3140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I think [this issue](https://github.com/nestjs/swagger/issues/2117) was closed without a real fix. When trying to generate a Swagger document, it will create `required` fields as a boolean rather than an array, for example if you defined a class like this:

```
class AddressResponseDTO {
  status: string;
  data: {
    line1: string;
    line2?: string;
    city: string;
    province?: string;
    postalCode: string;
    country: string;
  };
}
```

it generates the following:

{"type":"object","properties":{"status":{"type":"string"},"data":{"type":"object","properties":{"line1":{"type":"string","minLength":1,"required":true},"line2":{"type":"string","required":true},"city":{"type":"string","minLength":1,"required":true},"province":{"type":"string","required":true},"postalCode":{"type":"string","minLength":1,"required":true},"country":{"type":"string","minLength":1,"required":true}}}},"required":["status","data"]}

### Minimum reproduction code

https://github.com/nestjs/swagger/issues/2117

### Steps to reproduce

1. Define a class with a nested object or array of objects as the response type
2. Generate a Swagger document
3. Observe required fields are boolean when required fields should be defined by a separate array

### Expected behavior

The `required` field should only ever be an array, not a boolean

### Package version

8.0.1

### NestJS version

10.4.5

### Node.js version

20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have identified the issue and made the necessary changes to fix the generation of required fields for nested objects. The problem was in the `SchemaObjectFactory` class, specifically in the `createSchemaMetadata` method. I've updated the logic to correctly handle required fields for nested objects and arrays.

Here's a summary of the changes:

1. Updated the `createSchemaMetadata` method to handle nested objects and arrays correctly.
2. Modified the `transformToArraySchemaProperty` method to preserve the `required` field.
3. Updated the `createFromObjectLiteral` method to handle nested required fields.

These changes should resolve the issue of required fields being generated as boolean instead of an array for nested objects.

I also created pull request: https://github.com/nestjs/swagger/pull/3141


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by kamilmysliwiec** [comment]
I can't reproduce this issue. 

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project). The one from https://github.com/nestjs/swagger/issues/2117 is inccorect
