### ISSUE TITLE
External Dtos (i.e. in node_modules) do not keep Api Property options

### ISSUE THREAD

**Issue by cjancsar** [nestjs/swagger#580]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ X ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
This behaviour: https://github.com/nestjs/swagger/issues/529

Dtos from within the `src` folder are rendered with optional properties as optional. Dtos from outside the `src` folder (that have been created and compiled with nest) are rendered as required:
![image](https://user-images.githubusercontent.com/51799534/75029972-23fc5b00-5471-11ea-8aa2-6984aa074fcc.png)

## Expected behavior
Since the js of the compiled EXTERNAL dtos have references to `IsOptional`, and also have the language specifc '?' syntax before them, they should be shown as optional.

## Minimal reproduction of the problem with instructions
**Attached is a repo:** https://github.com/cjancsar/regression-external-dto-nestjs
Note: it pulls the external DTO from the published package here: 
- https://github.com/cjancsar/regression-common
- https://www.npmjs.com/package/regression-external-dto

## What is the motivation / use case for changing the behavior?
This is a bug.

## Environment

<pre><code>
Nest version: 6.11.8 (common)

 
Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
I've already replied to this issue and you ignored my response. 

This is not a bug - Plugin won't run for `node_modules`. If you have external packages which export DTOs, all its files should be **already compiled with Nest CLI, and hence, have the metadata in the generated JS files**. Thus, `@nestjs/swagger` will use this **pregenerated metadata**. Just ensure to compile packages with Nest CLI (and plugin enabled) instead of `tsc`. TypeScript compiler won't generate & modify AST for your JS files from node_modules, this would be ridiculous.

**Comment by cjancsar** [comment]
Please reopen. This is definitely a bug. The meta data exists in the external dto (see image, and see the minimal example that I spent time to create as per your previous request).
![image](https://user-images.githubusercontent.com/51799534/75031370-1694a000-5474-11ea-93d7-cb4ad1e7e54f.png)

**Comment by cjancsar** [comment]
@kamilmysliwiec see update, I think you closed this a little to passionately without actually looking into it.

**Comment by kamilmysliwiec** [comment]
I saw your screenshot and repository. As I said, this is not a bug. Please, read my message once again. Important note: metadata generated by the CLI != decorators from the `class-validator` library/design-time TSC metadata. 

As I've posted above:

- *ensure to compile packages with Nest CLI (and plugin enabled) instead of tsc**

**Comment by cjancsar** [comment]
Thanks @kamilmysliwiec 

I will have to come back to this then. I can't currently use the nest cli in our common package as there is some lingering legacy code in there. We are migrating to nest, so once I can compile it with the cli, then hopefully all will be good.
