### ISSUE TITLE
@nest/swagger example does not work in my wsl2

### ISSUE THREAD

**Issue by yjl9903** [nestjs/swagger#861]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

I tried the official working example in my wsl2. After I started the nest app and go to http://localhost:3000/api/, I clicked any route in cats tag, then the page flashed and this route went to default tag, and the current url is http://localhost:3000/api/#/default/post_cats. Then, I clicked this route, it will keep loadding like the flowing picture.

![image](https://user-images.githubusercontent.com/30072175/88148173-ce4ef900-cc30-11ea-81ce-a4da6681f0ea.png)

The nest log is:

```
yarn run v1.22.4
$ nest start
[Nest] 17403   - 07/22/2020, 3:16:25 PM   [NestFactory] Starting Nest application...
[Nest] 17403   - 07/22/2020, 3:16:25 PM   [InstanceLoader] AppModule dependencies initialized +10ms
[Nest] 17403   - 07/22/2020, 3:16:25 PM   [InstanceLoader] CatsModule dependencies initialized +0ms
[Nest] 17403   - 07/22/2020, 3:16:25 PM   [RoutesResolver] CatsController {/cats}: +39ms
[Nest] 17403   - 07/22/2020, 3:16:25 PM   [RouterExplorer] Mapped {/cats, POST} route +2ms
[Nest] 17403   - 07/22/2020, 3:16:25 PM   [RouterExplorer] Mapped {/cats/:id, GET} route +1ms
[Nest] 17403   - 07/22/2020, 3:16:25 PM   [NestApplication] Nest application successfully started +1ms
Application is running on: http://[::1]:3000
```

There is not log in the browser.

## Expected behavior

I want to see the detailed route infomation.

## Minimal reproduction of the problem with instructions

Official working [example](https://github.com/nestjs/nest/tree/master/sample/11-swagger).

## Environment

<pre><code>
Nest version: 7.3.2

 
For Tooling issues:
- Node version: 14.5.0  
- Platform:  Windows Subsystem for Linux 2, Ubuntu-20.04, Linux 4.19.104-microsoft-standard,  Windows10 2004 

Others:

</code></pre>

**Comment by chaims** [comment]
I have the same problem

**Comment by chaims** [comment]
change [swagger-ui-dist version "3.30.1"]  to  [version "3.26.2"] can resolve this problem

**Comment by julien-sugg** [comment]
This issue is indeed related to the `swagger-ui-dist`. Please note that an issue is already raised on their [bug tracker](https://github.com/swagger-api/swagger-ui/issues/6249).

As a workaround you can leverage [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) and add the following to your `package.json` as stated [here](https://github.com/swagger-api/swagger-ui/issues/6249#issuecomment-662423121)

```json
...
  "resolutions": {
    "swagger-ui-dist": "3.30.0"
  }
...
```

**Comment by yjl9903** [comment]
Thanks to @julien-sugg @chaims .

I will pay attention to this [bug tracker](https://github.com/swagger-api/swagger-ui/issues/6249).

**Comment by kamilmysliwiec** [comment]
This should be fixed in the `swagger-ui-dist@3.30.2` https://github.com/swagger-api/swagger-ui/issues/6249

**Comment by bilal-tekhqs** [comment]
Hi I have encountered a wired issue something like this but different in such a way that, I am sharing schemas as $ref in multiple endpoints. the issue is when I pass the schema as $ref in one endpoints example it shows up fine n swagger but when I pass the same schema in the second endpoints example it throughs error as follows:
![image](https://user-images.githubusercontent.com/108715506/182295249-917e2807-df5b-4f9b-bd0c-c895cc4cbe73.png)

the working example is:
![localhost_1349_api_swagger_ (1)](https://user-images.githubusercontent.com/108715506/182295792-9fbdbb7d-59c9-44e8-af48-baadd4e4c5a4.png)
kindly help me here 
this is my one endpoint
![image](https://user-images.githubusercontent.com/108715506/182295971-67596665-59d7-47fe-9e84-43eb6a540da6.png)
& this is the other endpoint.both located in one file
![image](https://user-images.githubusercontent.com/108715506/182296045-5fecd828-dc19-402c-af3c-cfdf14618120.png)
any help would be appreciated thanks

**Comment by bilal-tekhqs** [comment]
@kamilmysliwiec kindly respond

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
