### ISSUE TITLE
Some DTO won't show in the Swagger Schema

### ISSUE THREAD

**Issue by vh13294** [nestjs/swagger#954]
## Current behavior
I am using NestJS Swagger module to list api end points.
Some DTO won't show in the Swagger Schema.

## Input Code
https://github.com/vh13294/nestjs-inventory

As you can see "FindSingleLocationInventoryDto" is not shown.

<img width="1509" alt="Screen Shot 2020-09-07 at 9 12 19 PM" src="https://user-images.githubusercontent.com/17086745/92396592-753f1400-f14f-11ea-9d62-3d30714f2aa6.png">

<img width="1544" alt="Screen Shot 2020-09-07 at 9 13 38 PM" src="https://user-images.githubusercontent.com/17086745/92396621-8425c680-f14f-11ea-870c-81ed7d52538f.png">

<img width="548" alt="Screen Shot 2020-09-07 at 9 14 20 PM" src="https://user-images.githubusercontent.com/17086745/92396636-8be56b00-f14f-11ea-8111-198afd20ddaa.png">

I did run "npm build" several times. Still, it shows the same result.

## Environment

<pre><code>
Nest version: 7.4.4
 
For Tooling issues:
- Node version: v12.18.3
- Platform:  macOS catalina

**Comment by vh13294** [comment]
After playing around with it.
It turns out that Swagger Schema only shows the DTO that are wrapped within "@Body()" decorate.
Is that intended?

not "@Query()" nor "@Param()"

**Comment by GhyslainBruno** [comment]
Hi all, 

First of all, many thanks for your amazing work, NestJs (and you guys) rocks 🥇 !

As @vh13294 said, I can confirm that only DTOs wrapped within `@Body()` decorator are shown in the "Schema" part of the Swagger UI, but none of those wrapped within `@Query()` or `@Param()` decorators are (for my personal use case at the very least). 

@jmcdo29 or @kamilmysliwiec do you have some info about it ? Or any way we can get to do what we want ? 

I've seen several issues discussing about this weird behaviour (such as [114](https://github.com/nestjs/swagger/issues/114) and [299](https://github.com/nestjs/swagger/issues/299)) but all of them were _locked as off topic and limited to collaborators_, why such a thing ? 

Being able to provide an API documentation with every needed DTOs seems pretty relevant to me, isn't it ?

**Comment by jmcdo29** [comment]
As I said before, the `schemas` section is meant to be reserved for request bodies that are to be sent over the wire. However, that doesn't mean your swagger file is any less documented than if the `@Query()` and `@Param()` dtos were added to the schemas, because in each request, each route, there's information about what url and query parameters are to be expected, and swagger codegen does still operate fully (currently using it at my place of work). Is there a reason you think that it should be in the `schemas` vs where it currently is (with each route). [Even most of the examples in the Swagger docs](https://swagger.io/docs/specification/describing-parameters/) use inline for url and query parameters and schema refs for bodies and response bodies.

> all of them were _locked as off topic..._ why such a thing?

Because people can get really whiny when you tell them this isn't a bug and they'll generate a lot of noise that distracts us from enhancements. Nest is an opinionated framework, and it's our opinion that this is how we should set up the swagger document. You could always write some transformation code if you really feel the need to, but at the end of the day, what we have running works, and is pretty clean on the swagger side of things, in my opinion.

**Comment by dginzbourg** [comment]
One of the solutions is to use  @ApiExtraModels() decorator in controller.
e.g. 
`@ApiExtraModels(PageQueryDto, PageResponseDto, SomeApiDto)
@Controller('someapi')
export class SomeAPIController {
}

**Comment by johnitvn** [comment]
Use `@ApiProperty()` will resolve this issue


```
import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsOptional, IsInt, Min, Max } from 'class-validator';

export class PaginatedQueryDto {
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  @Min(1)
  @ApiProperty()
  page?: number = 1;

  @IsOptional()
  @IsInt()
  @Type(() => Number)
  @Min(1)
  @Max(100)
  @ApiProperty()
  limit?: number = 100;
}
```

```
  @Get()
  @ApiOperation({ summary: 'Retrieve all teams', description: '', tags: ['Team'] })
  async findlAll(
    @Query() query: PaginatedQueryDto,
  ): Promise<{ teams: TeamEntity[]; total: number }> {
    const [teams, total] = await this.teamService.findAllAndCount(query.page, query.limit);
    return { teams, total };
  }
````
